"""create stage runs and artifacts

Revision ID: e805b98d2288
Revises: 05eae40afbe7
Create Date: 2026-10-05 23:44:29.153350

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e805b98d2288"
down_revision: str | Sequence[str] | None = "05eae40afbe7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stage_runs",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "RESEARCH",
                "DEFINITION",
                "DESIGN",
                "IMPLEMENTATION",
                "VERIFICATION",
                "DONE",
                name="stage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="stagerunstatus",
                native_enum=False,
                length=32,
            ),
            server_default="RUNNING",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_item_id"], ["work_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stage_runs_work_item_id"), "stage_runs", ["work_item_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stage_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RESEARCH_BRIEF",
                "PRD",
                "ACCEPTANCE_CRITERIA",
                "TECH_DESIGN",
                "ADR",
                "UX_SPEC",
                "WIREFRAME",
                "IMPLEMENTATION",
                "TEST_CASES",
                "VERIFICATION_REPORT",
                name="artifactkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stage_run_id"], ["stage_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_stage_run_id"), "artifacts", ["stage_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_stage_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_stage_runs_work_item_id"), table_name="stage_runs")
    op.drop_table("stage_runs")
    # ### end Alembic commands ###
